// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by Embeddinator-4000.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
#include "Java.Interop.h"
#include "glib.h"
#include "mono_embeddinator.h"
#include "c-support.h"

mono_embeddinator_context_t __mono_context;
MonoImage* __Java_Interop_dll_image;

static MonoClass* class_Java_Interop_IJavaPeerable = 0;
static MonoClass* class_Java_Interop_JniManagedPeerStates = 0;
static MonoClass* class_System_IDisposable = 0;

static void __initialize_mono()
{
    if (__mono_context.domain)
        return;
    mono_embeddinator_init(&__mono_context, "mono_embeddinator_binding");
}

static void __lookup_assembly_Java_Interop_dll()
{
    if (__Java_Interop_dll_image)
        return;
    __Java_Interop_dll_image = mono_embeddinator_load_assembly(&__mono_context, "Java.Interop.dll");
}
