// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by Embeddinator-4000.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
#pragma once

#include "glib.h"
#include "mono_embeddinator.h"
#include "c-support.h"
#include "mscorlib.h"

MONO_EMBEDDINATOR_BEGIN_DECLS

typedef MonoEmbedObject Java_Interop_IJavaPeerable;

MONO_EMBEDDINATOR_END_DECLS
