// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by Embeddinator-4000.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
#pragma once

#include "glib.h"
#include "mono_embeddinator.h"
#include "c-support.h"
#include "Java.Interop.h"
#include "mscorlib.h"

MONO_EMBEDDINATOR_BEGIN_DECLS

typedef MonoEmbedObject Android_App_Activity;
typedef MonoEmbedObject Android_Views_ContextThemeWrapper;
typedef MonoEmbedObject Android_Content_ContextWrapper;
typedef MonoEmbedObject Android_Content_Context;
typedef MonoEmbedObject Java_Lang_Object;
typedef MonoEmbedObject Android_Runtime_IJavaObject;
typedef MonoEmbedObject Java_Interop_IJavaObjectEx;
typedef MonoEmbedObject Android_Content_IComponentCallbacks;
typedef MonoEmbedObject Android_Content_IComponentCallbacks2;
typedef MonoEmbedObject Android_Views_ICallback;
typedef MonoEmbedObject Android_Views_IFactory;
typedef MonoEmbedObject Android_Views_IFactory2;
typedef MonoEmbedObject Android_Views_IOnCreateContextMenuListener;

MONO_EMBEDDINATOR_END_DECLS
